#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := udp-multicast

CFLAGS := -DCONFIG_MDNS

include $(IDF_PATH)/make/project.mk

