/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

// Touch channels

#define TOUCH_PAD_GPIO6_CHANNEL     0
#define TOUCH_PAD_NUM0_GPIO_NUM     6

#define TOUCH_PAD_GPIO7_CHANNEL     1
#define TOUCH_PAD_NUM1_GPIO_NUM     7

#define TOUCH_PAD_GPIO8_CHANNEL     2
#define TOUCH_PAD_NUM2_GPIO_NUM     8

#define TOUCH_PAD_GPIO9_CHANNEL     3
#define TOUCH_PAD_NUM3_GPIO_NUM     9

#define TOUCH_PAD_GPIO10_CHANNEL    4
#define TOUCH_PAD_NUM4_GPIO_NUM     10

#define TOUCH_PAD_GPIO11_CHANNEL    5
#define TOUCH_PAD_NUM5_GPIO_NUM     11

#define TOUCH_PAD_GPIO12_CHANNEL    6
#define TOUCH_PAD_NUM6_GPIO_NUM     12

#define TOUCH_PAD_GPIO13_CHANNEL    7
#define TOUCH_PAD_NUM7_GPIO_NUM     13

#define TOUCH_PAD_GPIO14_CHANNEL    8
#define TOUCH_PAD_NUM8_GPIO_NUM     14

#define TOUCH_PAD_GPIO15_CHANNEL    9
#define TOUCH_PAD_NUM9_GPIO_NUM     15

#define TOUCH_PAD_GPIO16_CHANNEL    10
#define TOUCH_PAD_NUM10_GPIO_NUM    16

#define TOUCH_PAD_GPIO17_CHANNEL    11
#define TOUCH_PAD_NUM11_GPIO_NUM    17

#define TOUCH_PAD_GPIO18_CHANNEL    12
#define TOUCH_PAD_NUM12_GPIO_NUM    18

#define TOUCH_PAD_GPIO19_CHANNEL    13
#define TOUCH_PAD_NUM13_GPIO_NUM    19
