set(SOC_SRCS "cpu_util.c"
    "gpio_periph.c"
    "rtc_clk.c"
    "rtc_clk_init.c"
    "rtc_init.c"
    "rtc_periph.c"
    "rtc_pm.c"
    "rtc_sleep.c"
    "rtc_time.c"
    "rtc_wdt.c"
    "sdio_slave_periph.c"
    "sdmmc_periph.c"
    "soc_memory_layout.c"
    "spi_periph.c")