# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wifi_config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import constants_pb2 as constants__pb2
import wifi_constants_pb2 as wifi__constants__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11wifi_config.proto\x1a\x0f\x63onstants.proto\x1a\x14wifi_constants.proto\"\x0e\n\x0c\x43mdGetStatus\"\xb2\x01\n\rRespGetStatus\x12\x17\n\x06status\x18\x01 \x01(\x0e\x32\x07.Status\x12$\n\tsta_state\x18\x02 \x01(\x0e\x32\x11.WifiStationState\x12/\n\x0b\x66\x61il_reason\x18\n \x01(\x0e\x32\x18.WifiConnectFailedReasonH\x00\x12(\n\tconnected\x18\x0b \x01(\x0b\x32\x13.WifiConnectedStateH\x00\x42\x07\n\x05state\"P\n\x0c\x43mdSetConfig\x12\x0c\n\x04ssid\x18\x01 \x01(\x0c\x12\x12\n\npassphrase\x18\x02 \x01(\x0c\x12\r\n\x05\x62ssid\x18\x03 \x01(\x0c\x12\x0f\n\x07\x63hannel\x18\x04 \x01(\x05\"(\n\rRespSetConfig\x12\x17\n\x06status\x18\x01 \x01(\x0e\x32\x07.Status\"\x10\n\x0e\x43mdApplyConfig\"*\n\x0fRespApplyConfig\x12\x17\n\x06status\x18\x01 \x01(\x0e\x32\x07.Status\"\xd7\x02\n\x11WiFiConfigPayload\x12\x1f\n\x03msg\x18\x01 \x01(\x0e\x32\x12.WiFiConfigMsgType\x12\x12\n\nauth_token\x18\t \x01(\x0c\x12\'\n\x0e\x63md_get_status\x18\n \x01(\x0b\x32\r.CmdGetStatusH\x00\x12)\n\x0fresp_get_status\x18\x0b \x01(\x0b\x32\x0e.RespGetStatusH\x00\x12\'\n\x0e\x63md_set_config\x18\x0c \x01(\x0b\x32\r.CmdSetConfigH\x00\x12)\n\x0fresp_set_config\x18\r \x01(\x0b\x32\x0e.RespSetConfigH\x00\x12+\n\x10\x63md_apply_config\x18\x0e \x01(\x0b\x32\x0f.CmdApplyConfigH\x00\x12-\n\x11resp_apply_config\x18\x0f \x01(\x0b\x32\x10.RespApplyConfigH\x00\x42\t\n\x07payload*\x9e\x01\n\x11WiFiConfigMsgType\x12\x14\n\x10TypeCmdGetStatus\x10\x00\x12\x15\n\x11TypeRespGetStatus\x10\x01\x12\x14\n\x10TypeCmdSetConfig\x10\x02\x12\x15\n\x11TypeRespSetConfig\x10\x03\x12\x16\n\x12TypeCmdApplyConfig\x10\x04\x12\x17\n\x13TypeRespApplyConfig\x10\x05\x62\x06proto3')

_WIFICONFIGMSGTYPE = DESCRIPTOR.enum_types_by_name['WiFiConfigMsgType']
WiFiConfigMsgType = enum_type_wrapper.EnumTypeWrapper(_WIFICONFIGMSGTYPE)
TypeCmdGetStatus = 0
TypeRespGetStatus = 1
TypeCmdSetConfig = 2
TypeRespSetConfig = 3
TypeCmdApplyConfig = 4
TypeRespApplyConfig = 5


_CMDGETSTATUS = DESCRIPTOR.message_types_by_name['CmdGetStatus']
_RESPGETSTATUS = DESCRIPTOR.message_types_by_name['RespGetStatus']
_CMDSETCONFIG = DESCRIPTOR.message_types_by_name['CmdSetConfig']
_RESPSETCONFIG = DESCRIPTOR.message_types_by_name['RespSetConfig']
_CMDAPPLYCONFIG = DESCRIPTOR.message_types_by_name['CmdApplyConfig']
_RESPAPPLYCONFIG = DESCRIPTOR.message_types_by_name['RespApplyConfig']
_WIFICONFIGPAYLOAD = DESCRIPTOR.message_types_by_name['WiFiConfigPayload']
CmdGetStatus = _reflection.GeneratedProtocolMessageType('CmdGetStatus', (_message.Message,), {
  'DESCRIPTOR' : _CMDGETSTATUS,
  '__module__' : 'wifi_config_pb2'
  # @@protoc_insertion_point(class_scope:CmdGetStatus)
  })
_sym_db.RegisterMessage(CmdGetStatus)

RespGetStatus = _reflection.GeneratedProtocolMessageType('RespGetStatus', (_message.Message,), {
  'DESCRIPTOR' : _RESPGETSTATUS,
  '__module__' : 'wifi_config_pb2'
  # @@protoc_insertion_point(class_scope:RespGetStatus)
  })
_sym_db.RegisterMessage(RespGetStatus)

CmdSetConfig = _reflection.GeneratedProtocolMessageType('CmdSetConfig', (_message.Message,), {
  'DESCRIPTOR' : _CMDSETCONFIG,
  '__module__' : 'wifi_config_pb2'
  # @@protoc_insertion_point(class_scope:CmdSetConfig)
  })
_sym_db.RegisterMessage(CmdSetConfig)

RespSetConfig = _reflection.GeneratedProtocolMessageType('RespSetConfig', (_message.Message,), {
  'DESCRIPTOR' : _RESPSETCONFIG,
  '__module__' : 'wifi_config_pb2'
  # @@protoc_insertion_point(class_scope:RespSetConfig)
  })
_sym_db.RegisterMessage(RespSetConfig)

CmdApplyConfig = _reflection.GeneratedProtocolMessageType('CmdApplyConfig', (_message.Message,), {
  'DESCRIPTOR' : _CMDAPPLYCONFIG,
  '__module__' : 'wifi_config_pb2'
  # @@protoc_insertion_point(class_scope:CmdApplyConfig)
  })
_sym_db.RegisterMessage(CmdApplyConfig)

RespApplyConfig = _reflection.GeneratedProtocolMessageType('RespApplyConfig', (_message.Message,), {
  'DESCRIPTOR' : _RESPAPPLYCONFIG,
  '__module__' : 'wifi_config_pb2'
  # @@protoc_insertion_point(class_scope:RespApplyConfig)
  })
_sym_db.RegisterMessage(RespApplyConfig)

WiFiConfigPayload = _reflection.GeneratedProtocolMessageType('WiFiConfigPayload', (_message.Message,), {
  'DESCRIPTOR' : _WIFICONFIGPAYLOAD,
  '__module__' : 'wifi_config_pb2'
  # @@protoc_insertion_point(class_scope:WiFiConfigPayload)
  })
_sym_db.RegisterMessage(WiFiConfigPayload)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WIFICONFIGMSGTYPE._serialized_start=790
  _WIFICONFIGMSGTYPE._serialized_end=948
  _CMDGETSTATUS._serialized_start=60
  _CMDGETSTATUS._serialized_end=74
  _RESPGETSTATUS._serialized_start=77
  _RESPGETSTATUS._serialized_end=255
  _CMDSETCONFIG._serialized_start=257
  _CMDSETCONFIG._serialized_end=337
  _RESPSETCONFIG._serialized_start=339
  _RESPSETCONFIG._serialized_end=379
  _CMDAPPLYCONFIG._serialized_start=381
  _CMDAPPLYCONFIG._serialized_end=397
  _RESPAPPLYCONFIG._serialized_start=399
  _RESPAPPLYCONFIG._serialized_end=441
  _WIFICONFIGPAYLOAD._serialized_start=444
  _WIFICONFIGPAYLOAD._serialized_end=787
# @@protoc_insertion_point(module_scope)
