.. list-table::
  :header-rows: 1
  :widths: 20 10 10 20 20 20

  * - CPU frequency
    - DFS
    - DTIM
    - Average current(mA)
    - Max current(mA)
    - Min current(mA)

  * - 120 MHz
    - ON
    - 1
    - 7.5
    - 65.9
    - 6.0

  * - 120 MHz
    - OFF
    - 1
    - 13.6
    - 221.5
    - 12.6

  * - 120 MHz
    - ON
    - 3
    - 6.9
    - 65.4
    - 6.0

  * - 120 MHz
    - OFF
    - 3
    - 13.0
    - 220.2
    - 12.6

  * - 120 MHz
    - ON
    - 10
    - 6.6
    - 64.9
    - 6.0

  * - 120 MHz
    - OFF
    - 10
    - 12.9
    - 216.8
    - 12.6
