.. list-table::
  :header-rows: 1
  :widths: 20 10 10 20 20 20

  * - CPU frequency
    - DFS
    - DTIM
    - Average current(mA)
    - Max current(mA)
    - Min current(mA)

  * - 160 MHz
    - ON
    - 1
    - 20.7
    - 113.5
    - 15.0

  * - 160 MHz
    - OFF
    - 1
    - 40.1
    - 235.8
    - 37.8

  * - 160 MHz
    - ON
    - 3
    - 19.9
    - 113.4
    - 15.0

  * - 160 MHz
    - OFF
    - 3
    - 38.7
    - 267.2
    - 37.9

  * - 160 MHz
    - ON
    - 10
    - 19.5
    - 113.4
    - 15.0

  * - 160 MHz
    - OFF
    - 10
    - 38.2
    - 259.7
    - 37.9
