.. list-table::
  :header-rows: 1
  :widths: 20 10 10 20 20 20

  * - CPU frequency
    - DFS
    - DTIM
    - Average current(mA)
    - Max current(mA)
    - Min current(mA)

  * - 160 MHz
    - ON
    - 1
    - /
    - /
    - /

  * - 160 MHz
    - OFF
    - 1
    - /
    - /
    - /

  * - 160 MHz
    - ON
    - 3
    - /
    - /
    - /

  * - 160 MHz
    - OFF
    - 3
    - /
    - /
    - /

  * - 160 MHz
    - ON
    - 10
    - /
    - /
    - /

  * - 160 MHz
    - OFF
    - 10
    - /
    - /
    - /
