.. list-table::
  :header-rows: 1
  :widths: 20 10 10 20 20 20

  * - CPU frequency
    - DFS
    - DTIM
    - Average current(mA)
    - Max current(mA)
    - Min current(mA)

  * - 160 MHz
    - ON
    - 1
    - 11.35
    - 83.31
    - 5.03

  * - 160 MHz
    - OFF
    - 1
    - 21.47
    - 191.53
    - 20.58

  * - 160 MHz
    - ON
    - 3
    - 10.71
    - 82.82
    - 5.09

  * - 160 MHz
    - OFF
    - 3
    - 20.82
    - 82.98
    - 20.48

  * - 160 MHz
    - ON
    - 10
    - 10.32
    - 81.05
    - 5.74

  * - 160 MHz
    - OFF
    - 10
    - 20.67
    - 229.83
    - 20.48
