.. list-table::
  :header-rows: 1
  :widths: 20 10 10 20 20 20

  * - CPU frequency
    - DFS
    - DTIM
    - Average current(mA)
    - Max current(mA)
    - Min current(mA)

  * - 160 MHz
    - ON
    - 1
    - 19.66
    - 96.14
    - 15.04

  * - 160 MHz
    - OFF
    - 1
    - 35.31
    - 95.41
    - 34.74

  * - 160 MHz
    - ON
    - 3
    - 19.16
    - 96.7
    - 15.07

  * - 160 MHz
    - OFF
    - 3
    - 34.87
    - 95.76
    - 34.74

  * - 160 MHz
    - ON
    - 10
    - 18.99
    - 95.93
    - 15.05

  * - 160 MHz
    - OFF
    - 10
    - 34.74
    - 95.77
    - 34.71
