.. list-table::
  :header-rows: 1
  :widths: 20 10 10 20 20 20

  * - CPU frequency
    - DFS
    - DTIM
    - Average current(mA)
    - Max current(mA)
    - Min current(mA)

  * - 160 MHz
    - ON
    - 1
    - 11.71
    - 83.87
    - 5.04

  * - 160 MHz
    - OFF
    - 1
    - 31.14
    - 160.26
    - 29.04

  * - 160 MHz
    - ON
    - 3
    - 12.4
    - 84.85
    - 10.0

  * - 160 MHz
    - OFF
    - 3
    - 29.06
    - 178.67
    - 28.25

  * - 160 MHz
    - ON
    - 10
    - 12.15
    - 84.18
    - 10.01

  * - 160 MHz
    - OFF
    - 10
    - 28.5
    - 176.69
    - 28.21
