.. list-table::
  :header-rows: 1
  :widths: 20 10 10 20 20 20

  * - CPU frequency
    - DFS
    - DTIM
    - Average current(mA)
    - Max current(mA)
    - Min current(mA)

  * - 160 MHz
    - ON
    - 1
    - 22.65
    - 133.03
    - 5.48

  * - 160 MHz
    - OFF
    - 1
    - 31.12
    - 253.74
    - 27.18

  * - 160 MHz
    - ON
    - 3
    - 21.89
    - 247.68
    - 5.25

  * - 160 MHz
    - OFF
    - 3
    - 28.81
    - 209.42
    - 27.77

  * - 160 MHz
    - ON
    - 10
    - 20.01
    - 216.51
    - 6.02

  * - 160 MHz
    - OFF
    - 10
    - 29.66
    - 114.17
    - 27.77
