.. list-table::
  :header-rows: 1
  :widths: 20 10 10 20 20 20

  * - CPU frequency
    - DFS
    - DTIM
    - Average current(mA)
    - Max current(mA)
    - Min current(mA)

  * - 160 MHz
    - ON
    - 1
    - 22.07
    - 98.64
    - 17.23

  * - 160 MHz
    - OFF
    - 1
    - 38.44
    - 99.99
    - 37.83

  * - 160 MHz
    - ON
    - 3
    - 21.55
    - 98.58
    - 17.38

  * - 160 MHz
    - OFF
    - 3
    - 37.99
    - 100.01
    - 37.83

  * - 160 MHz
    - ON
    - 10
    - 21.36
    - 98.9
    - 17.25

  * - 160 MHz
    - OFF
    - 10
    - 37.84
    - 98.94
    - 37.86
