include $(COMPONENT_PATH)/Makefile.files

COMPONENT_OWNBUILDTARGET := 1
COMPONENT_OWNCLEANTARGET := 1

COMPONENT_ADD_INCLUDEDIRS := $(INCLUDE_DIRS)

.PHONY: build
build: $(SDKCONFIG_HEADER)
	$(MAKE) -C $(COMPONENT_PATH) lib SDKCONFIG=$(SDKCONFIG_HEADER) BUILD_DIR=$(COMPONENT_BUILD_DIR) COMPONENT=$(COMPONENT_NAME)

CLEAN_FILES := component_project_vars.mk
.PHONY: clean
clean:
	$(summary) RM $(CLEAN_FILES)
	rm -f $(CLEAN_FILES)
	$(MAKE) -C $(COMPONENT_PATH) clean SDKCONFIG=$(SDKCONFIG_HEADER) BUILD_DIR=$(COMPONENT_BUILD_DIR) COMPONENT=$(COMPONENT_NAME)
