#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := ble_mesh_wifi_coexist

EXTRA_COMPONENT_DIRS := $(IDF_PATH)/examples/bluetooth/esp_ble_mesh/components/example_init \
                        $(IDF_PATH)/examples/bluetooth/esp_ble_mesh/components/fast_provisioning

include $(IDF_PATH)/make/project.mk
