#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := ble_mesh_wifi_coexist

COMPONENT_ADD_INCLUDEDIRS := components/include

EXTRA_COMPONENT_DIRS := $(IDF_PATH)/examples/bluetooth/esp_ble_mesh/ble_mesh_vendor_models/fast_prov_vendor_model/components

include $(IDF_PATH)/make/project.mk
