SOURCE_FILES := \
	$(addprefix ../, \
	wear_levelling.cpp \
	crc32.cpp \
	WL_Flash.cpp \
	Partition.cpp \
	)

INCLUDE_DIRS := \
	. \
	../ \
	../include \
	../private_include \
	../../spi_flash/sim \
	$(addprefix ../../spi_flash/sim/stubs/, \
	app_update/include \
	driver/include \
	freertos/include \
	log/include \
	newlib/include \
	sdmmc/include \
	vfs/include \
	) \
	$(addprefix ../../../components/, \
	heap/include \
	esp_rom/include \
	esp_system/include \
	esp_common/include \
	esp_hw_support/include \
	esp_hw_support/include/soc \
	xtensa/include \
	xtensa/esp32/include \
	soc/esp32/include \
      	heap/include \
	soc/include \
	esp32/include \
	bootloader_support/include \
	bootloader_support/bootloader_flash/include \
	app_update/include \
	hal/include \
	spi_flash/include \
	esp_partition/include \
	)
