/*
 * SPDX-FileCopyrightText: 2010-2022 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

#define ADC1_GPIO1_CHANNEL     ADC1_CHANNEL_0
#define ADC1_CHANNEL_0_GPIO_NUM 1

#define ADC1_GPIO2_CHANNEL     ADC1_CHANNEL_1
#define ADC1_CHANNEL_1_GPIO_NUM 2

#define ADC1_GPIO3_CHANNEL     ADC1_CHANNEL_2
#define ADC1_CHANNEL_2_GPIO_NUM 3

#define ADC1_GPIO4_CHANNEL     ADC1_CHANNEL_3
#define ADC1_CHANNEL_3_GPIO_NUM 4

#define ADC1_GPIO5_CHANNEL     ADC1_CHANNEL_4
#define ADC1_CHANNEL_4_GPIO_NUM 5

#define ADC1_GPIO6_CHANNEL     ADC1_CHANNEL_5
#define ADC1_CHANNEL_5_GPIO_NUM 6

#define ADC1_GPIO7_CHANNEL     ADC1_CHANNEL_6
#define ADC1_CHANNEL_6_GPIO_NUM 7

#define ADC1_GPIO8_CHANNEL     ADC1_CHANNEL_7
#define ADC1_CHANNEL_7_GPIO_NUM 8

#define ADC1_GPIO9_CHANNEL     ADC1_CHANNEL_8
#define ADC1_CHANNEL_8_GPIO_NUM 9

#define ADC1_GPIO10_CHANNEL     ADC1_CHANNEL_9
#define ADC1_CHANNEL_9_GPIO_NUM 10

#define ADC2_GPIO11_CHANNEL      ADC2_CHANNEL_0
#define ADC2_CHANNEL_0_GPIO_NUM 11

#define ADC2_GPIO12_CHANNEL      ADC2_CHANNEL_1
#define ADC2_CHANNEL_1_GPIO_NUM 12

#define ADC2_GPIO13_CHANNEL      ADC2_CHANNEL_2
#define ADC2_CHANNEL_2_GPIO_NUM 13

#define ADC2_GPIO14_CHANNEL     ADC2_CHANNEL_3
#define ADC2_CHANNEL_3_GPIO_NUM 14

#define ADC2_GPIO15_CHANNEL     ADC2_CHANNEL_4
#define ADC2_CHANNEL_4_GPIO_NUM 15

#define ADC2_GPIO16_CHANNEL     ADC2_CHANNEL_5
#define ADC2_CHANNEL_5_GPIO_NUM 16

#define ADC2_GPIO17_CHANNEL     ADC2_CHANNEL_6
#define ADC2_CHANNEL_6_GPIO_NUM 17

#define ADC2_GPIO18_CHANNEL     ADC2_CHANNEL_7
#define ADC2_CHANNEL_7_GPIO_NUM 18

#define ADC2_GPIO19_CHANNEL     ADC2_CHANNEL_8
#define ADC2_CHANNEL_8_GPIO_NUM 19

#define ADC2_GPIO20_CHANNEL     ADC2_CHANNEL_9
#define ADC2_CHANNEL_9_GPIO_NUM 20
