#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := dpp-enrollee

EXTRA_COMPONENT_DIRS = $(IDF_PATH)/examples/common_components/qrcode

include $(IDF_PATH)/make/project.mk
