#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := iperf

EXTRA_COMPONENT_DIRS := $(IDF_PATH)/examples/system/console/advanced/components
EXTRA_COMPONENT_DIRS += $(IDF_PATH)/examples/common_components/iperf

include $(IDF_PATH)/make/project.mk
