#!/bin/bash

# This file gets executed to build the image on the Docker Hub.
# See https://docs.docker.com/docker-hub/builds/advanced/#build-hook-examples for details.

set -euo pipefail

echo "Building for branch ${SOURCE_BRANCH}, commit ${SOURCE_COMMIT}"

docker build \
    --build-arg IDF_CLONE_BRANCH_OR_TAG=${SOURCE_BRANCH} \
    --build-arg IDF_CHECKOUT_REF=${SOURCE_COMMIT} \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME .
