# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/console/test_apps/console:
  enable:
    - if: IDF_TARGET in["esp32", "esp32c3", "linux"]
      reason: Testing all major architectures
  depends_components:
    - console
    - esp_driver_uart
    - esp_driver_usb_serial_jtag
    - esp_usb_cdc_rom_console
    - esp_stdio
    - vfs

components/console/test_apps/usb_serial_jtag_repl_no_input:
  disable:
    - if: IDF_TARGET not in ["esp32c6"]
      reason: Single-target regression coverage to reduce CI load
  depends_components:
    - console
    - esp_driver_uart
    - esp_driver_usb_serial_jtag
