/*
 * SPDX-FileCopyrightText: 2015-2022 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

#define SDIO_SLAVE_SLOT0_IOMUX_PIN_NUM_CLK  6
#define SDIO_SLAVE_SLOT0_IOMUX_PIN_NUM_CMD  11
#define SDIO_SLAVE_SLOT0_IOMUX_PIN_NUM_D0   7
#define SDIO_SLAVE_SLOT0_IOMUX_PIN_NUM_D1   8
#define SDIO_SLAVE_SLOT0_IOMUX_PIN_NUM_D2   9
#define SDIO_SLAVE_SLOT0_IOMUX_PIN_NUM_D3   10
#define SDIO_SLAVE_SLOT0_FUNC               0

#define SDIO_SLAVE_SLOT1_IOMUX_PIN_NUM_CLK  14
#define SDIO_SLAVE_SLOT1_IOMUX_PIN_NUM_CMD  15
#define SDIO_SLAVE_SLOT1_IOMUX_PIN_NUM_D0   2
#define SDIO_SLAVE_SLOT1_IOMUX_PIN_NUM_D1   4
#define SDIO_SLAVE_SLOT1_IOMUX_PIN_NUM_D2   12
#define SDIO_SLAVE_SLOT1_IOMUX_PIN_NUM_D3   13
#define SDIO_SLAVE_SLOT1_FUNC               4
