#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#
PROJECT_NAME := modbus_tcp_slave

EXTRA_COMPONENT_DIRS := ../../../
EXTRA_COMPONENT_DIRS += ../../mb_example_common
EXTRA_COMPONENT_DIRS += $(IDF_PATH)/examples/common_components/protocol_examples_common
EXCLUDE_COMPONENTS := test freemodbus

include $(IDF_PATH)/make/project.mk
