#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := init1_mfg

CFLAGS += -DESPWROOM32SE
include $(IDF_PATH)/make/project.mk

