/*
 * SPDX-FileCopyrightText: 2015-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef __BLE_USER_CFG_H__
#define __BLE_USER_CFG_H__

#include <sdkconfig.h>
#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#if CONFIG_BT_NIMBLE_ENABLED
#include "syscfg/syscfg.h"
#endif

#if CONFIG_BT_NIMBLE_ENABLED

#if CONFIG_BT_NIMBLE_LL_CFG_FEAT_LE_CODED_PHY
#define BLE_LL_SCAN_PHY_NUMBER_N (2)
#else
#define BLE_LL_SCAN_PHY_NUMBER_N (1)
#endif
#define DEFAULT_BT_LE_MAX_PERIODIC_ADVERTISER_LIST MYNEWT_VAL(BLE_MAX_PERIODIC_ADVERTISER_LIST)
#define DEFAULT_BT_LE_MAX_PERIODIC_SYNCS MYNEWT_VAL(BLE_MAX_PERIODIC_SYNCS)
#define DEFAULT_BT_LE_MAX_CONNECTIONS MYNEWT_VAL(BLE_MAX_CONNECTIONS)
#define DEFAULT_BT_LE_ACL_BUF_SIZE MYNEWT_VAL(BLE_TRANSPORT_ACL_SIZE)
#define DEFAULT_BT_LE_ACL_BUF_COUNT MYNEWT_VAL(BLE_TRANSPORT_ACL_FROM_LL_COUNT)
#define DEFAULT_BT_LE_HCI_EVT_BUF_SIZE MYNEWT_VAL(BLE_TRANSPORT_EVT_SIZE)
#define DEFAULT_BT_LE_EXT_ADV_MAX_SIZE MYNEWT_VAL(BLE_EXT_ADV_MAX_SIZE)
#define DEFAULT_BT_LE_MAX_EXT_ADV_INSTANCES MYNEWT_VAL(BLE_MULTI_ADV_INSTANCES)
#define DEFAULT_BT_NIMBLE_WHITELIST_SIZE MYNEWT_VAL(BLE_LL_WHITELIST_SIZE)
#define DEFAULT_BT_LE_HCI_EVT_HI_BUF_COUNT MYNEWT_VAL(BLE_TRANSPORT_EVT_COUNT)
#define DEFAULT_BT_LE_HCI_EVT_LO_BUF_COUNT MYNEWT_VAL(BLE_TRANSPORT_EVT_DISCARDABLE_COUNT)
#define DEFAULT_BT_LE_COEX_PHY_CODED_TX_RX_TLIM_EFF CONFIG_BT_LE_COEX_PHY_CODED_TX_RX_TLIM_EFF
#else

#if CONFIG_BT_LE_LL_CFG_FEAT_LE_CODED_PHY
#define BLE_LL_SCAN_PHY_NUMBER_N (2)
#else
#define BLE_LL_SCAN_PHY_NUMBER_N (1)
#endif

#if defined(CONFIG_BT_LE_MAX_PERIODIC_ADVERTISER_LIST)
#define DEFAULT_BT_LE_MAX_PERIODIC_ADVERTISER_LIST (CONFIG_BT_LE_MAX_PERIODIC_ADVERTISER_LIST)
#else
#define DEFAULT_BT_LE_MAX_PERIODIC_ADVERTISER_LIST (5)
#endif

#if defined(CONFIG_BT_LE_MAX_PERIODIC_SYNCS)
#define DEFAULT_BT_LE_MAX_PERIODIC_SYNCS (CONFIG_BT_LE_MAX_PERIODIC_SYNCS)
#else
#define DEFAULT_BT_LE_MAX_PERIODIC_SYNCS (1)
#endif

#if defined(CONFIG_BT_LE_MAX_CONNECTIONS)
#define DEFAULT_BT_LE_MAX_CONNECTIONS (CONFIG_BT_LE_MAX_CONNECTIONS)
#else
#define DEFAULT_BT_LE_MAX_CONNECTIONS (2)
#endif

#if defined(CONFIG_BT_LE_ACL_BUF_SIZE)
#define DEFAULT_BT_LE_ACL_BUF_SIZE (CONFIG_BT_LE_ACL_BUF_SIZE)
#else
#define DEFAULT_BT_LE_ACL_BUF_SIZE (255)
#endif

#if defined(CONFIG_BT_LE_ACL_BUF_COUNT)
#define DEFAULT_BT_LE_ACL_BUF_COUNT (CONFIG_BT_LE_ACL_BUF_COUNT)
#else
#define DEFAULT_BT_LE_ACL_BUF_COUNT (24)
#endif

#if defined(CONFIG_BT_LE_HCI_EVT_BUF_SIZE)
#define DEFAULT_BT_LE_HCI_EVT_BUF_SIZE (CONFIG_BT_LE_HCI_EVT_BUF_SIZE)
#else
#define DEFAULT_BT_LE_HCI_EVT_BUF_SIZE (70)
#endif

#if defined(CONFIG_BT_LE_EXT_ADV_MAX_SIZE)
#define DEFAULT_BT_LE_EXT_ADV_MAX_SIZE (CONFIG_BT_LE_EXT_ADV_MAX_SIZE)
#else
#define DEFAULT_BT_LE_EXT_ADV_MAX_SIZE (31)
#endif

#if defined(CONFIG_BT_LE_MAX_EXT_ADV_INSTANCES)
#define DEFAULT_BT_LE_MAX_EXT_ADV_INSTANCES (CONFIG_BT_LE_MAX_EXT_ADV_INSTANCES)
#else
#define DEFAULT_BT_LE_MAX_EXT_ADV_INSTANCES (1)
#endif

#if defined(CONFIG_BT_LE_WHITELIST_SIZE)
#define DEFAULT_BT_NIMBLE_WHITELIST_SIZE (CONFIG_BT_LE_WHITELIST_SIZE)
#else
#define DEFAULT_BT_NIMBLE_WHITELIST_SIZE (12)
#endif

#if defined(CONFIG_BT_LE_HCI_EVT_HI_BUF_COUNT)
#define DEFAULT_BT_LE_HCI_EVT_HI_BUF_COUNT (CONFIG_BT_LE_HCI_EVT_HI_BUF_COUNT)
#else
#define DEFAULT_BT_LE_HCI_EVT_HI_BUF_COUNT (30)
#endif

#if defined(CONFIG_BT_LE_HCI_EVT_LO_BUF_COUNT)
#define DEFAULT_BT_LE_HCI_EVT_LO_BUF_COUNT (CONFIG_BT_LE_HCI_EVT_LO_BUF_COUNT)
#else
#define DEFAULT_BT_LE_HCI_EVT_LO_BUF_COUNT (8)
#endif

#define DEFAULT_BT_LE_COEX_PHY_CODED_TX_RX_TLIM_EFF CONFIG_BT_LE_COEX_PHY_CODED_TX_RX_TLIM_EFF
#endif // CONFIG_BT_NIMBLE_ENABLED

#ifdef CONFIG_BT_LE_TX_CCA_ENABLED
#define DEFAULT_BT_LE_TX_CCA_ENABLED (CONFIG_BT_LE_TX_CCA_ENABLED)
#else
#define DEFAULT_BT_LE_TX_CCA_ENABLED (0)
#endif

#ifdef CONFIG_BT_LE_CCA_RSSI_THRESH
#define DEFAULT_BT_LE_CCA_RSSI_THRESH (CONFIG_BT_LE_CCA_RSSI_THRESH)
#else
#define DEFAULT_BT_LE_CCA_RSSI_THRESH (50)
#endif

#define DEFAULT_BT_LE_SCAN_RSP_DATA_MAX_LEN_N DEFAULT_BT_LE_EXT_ADV_MAX_SIZE

#define UC_BLE_CTRL_CONN_ENABLED (1)

#if defined(CONFIG_BT_NIMBLE_AOA_AOD)
#define UC_BT_CTRL_LE_CTE_ENABLED (CONFIG_BT_NIMBLE_AOA_AOD)
#elif defined(CONFIG_BT_BLE_FEAT_CTE_EN)
#define UC_BT_CTRL_LE_CTE_ENABLED (CONFIG_BT_BLE_FEAT_CTE_EN)
#elif defined(CONFIG_BT_LE_CTE_FEATURE_ENABLED)
#define UC_BT_CTRL_LE_CTE_ENABLED (CONFIG_BT_LE_CTE_FEATURE_ENABLED)
#else
#define UC_BT_CTRL_LE_CTE_ENABLED (0)
#endif // CONFIG_BT_NIMBLE_AOA_AOD

#define UC_BT_CTRL_LE_CTE_CAL_ENABLED (0)

#if CONFIG_BT_LE_DTM_ENABLED
#define UC_BT_CTRL_LE_DTM_ENABLED (CONFIG_BT_LE_DTM_ENABLED)
#else
#define UC_BT_CTRL_LE_DTM_ENABLED (0)
#endif

#if defined(CONFIG_BT_NIMBLE_PERIODIC_ADV_WITH_RESPONSES)
#define UC_BLE_CTRL_PAWR_BCAST_SUPPORTED (CONFIG_BT_NIMBLE_PERIODIC_ADV_WITH_RESPONSES)
#elif defined(CONFIG_BT_BLE_FEAT_PAWR_EN)
#define UC_BLE_CTRL_PAWR_BCAST_SUPPORTED (CONFIG_BT_BLE_FEAT_PAWR_EN)
#elif defined(CONFIG_BT_LE_PERIODIC_ADV_WITH_RESPONSE_ENABLED)
#define UC_BLE_CTRL_PAWR_BCAST_SUPPORTED (CONFIG_BT_LE_PERIODIC_ADV_WITH_RESPONSE_ENABLED)
#else
#define UC_BLE_CTRL_PAWR_BCAST_SUPPORTED (0)
#endif // CONFIG_BT_NIMBLE_PERIODIC_ADV_WITH_RESPONSES

#if defined(CONFIG_BT_NIMBLE_PERIODIC_ADV_WITH_RESPONSES)
#define UC_BLE_CTRL_PAWR_SYNC_SUPPORTED (CONFIG_BT_NIMBLE_PERIODIC_ADV_WITH_RESPONSES)
#elif defined(CONFIG_BT_BLE_FEAT_PAWR_EN)
#define UC_BLE_CTRL_PAWR_SYNC_SUPPORTED (CONFIG_BT_BLE_FEAT_PAWR_EN)
#elif defined(CONFIG_BT_LE_PERIODIC_SYNC_WITH_RESPONSE_ENABLED)
#define UC_BLE_CTRL_PAWR_SYNC_SUPPORTED (CONFIG_BT_LE_PERIODIC_SYNC_WITH_RESPONSE_ENABLED)
#else
#define UC_BLE_CTRL_PAWR_SYNC_SUPPORTED (0)
#endif // CONFIG_BT_NIMBLE_PERIODIC_ADV_WITH_RESPONSES

#define UC_BT_CTRL_LE_BIS_BCAST_ENABLED (CONFIG_BT_LE_ISO_SUPPORT)
#define UC_BT_CTRL_LE_BIS_SYNC_ENABLED (CONFIG_BT_LE_ISO_SUPPORT)
#define UC_BT_CTRL_LE_CIS_CENT_ENABLED (CONFIG_BT_LE_ISO_SUPPORT)
#define UC_BT_CTRL_LE_CIS_PRPH_ENABLED (CONFIG_BT_LE_ISO_SUPPORT)
#define UC_BT_CTRL_LE_CIS_ENABLED (CONFIG_BT_LE_ISO_SUPPORT)
#define UC_BT_CTRL_LE_ISO_ENABLED (CONFIG_BT_LE_ISO_SUPPORT)
#define UC_BT_CTRL_LE_ISO_TEST_ENABLED (CONFIG_BT_LE_ISO_SUPPORT)

#if defined(CONFIG_BT_NIMBLE_50_FEATURE_SUPPORT)
#define UC_BT_CTRL_LE_50_FEATURE_SUPPORT (CONFIG_BT_NIMBLE_50_FEATURE_SUPPORT)
#elif defined(CONFIG_BT_LE_50_FEATURE_SUPPORT)
#define UC_BT_CTRL_LE_50_FEATURE_SUPPORT (CONFIG_BT_LE_50_FEATURE_SUPPORT)
#else
#define UC_BT_CTRL_LE_50_FEATURE_SUPPORT (0)
#endif // CONFIG_BT_NIMBLE_50_FEATURE_SUPPORT

#if defined(CONFIG_BT_NIMBLE_SUBRATE)
#define UC_BT_CTRL_LE_SUBRATE_ENABLED (CONFIG_BT_NIMBLE_SUBRATE)
#elif defined(CONFIG_BT_BLE_FEAT_CONN_SUBRATING)
#define UC_BT_CTRL_LE_SUBRATE_ENABLED (CONFIG_BT_BLE_FEAT_CONN_SUBRATING)
#elif defined(CONFIG_BT_LE_SUBRATE_ENABLED)
#define UC_BT_CTRL_LE_SUBRATE_ENABLED (CONFIG_BT_LE_SUBRATE_ENABLED)
#else
#define UC_BT_CTRL_LE_SUBRATE_ENABLED (0)
#endif // CONFIG_BT_NIMBLE_SUBRATE

#if defined(CONFIG_BT_NIMBLE_BLE_POWER_CONTROL)
#define UC_BT_CTRL_LE_POWER_CONTROL_ENABLED (CONFIG_BT_NIMBLE_BLE_POWER_CONTROL)
#elif defined(CONFIG_BT_LE_POWER_CONTROL_ENABLED)
#define UC_BT_CTRL_LE_POWER_CONTROL_ENABLED (CONFIG_BT_LE_POWER_CONTROL_ENABLED)
#else
#define UC_BT_CTRL_LE_POWER_CONTROL_ENABLED (0)
#endif // CONFIG_BT_NIMBLE_BLE_POWER_CONTROL

#if defined(CONFIG_BT_CTRL_LE_VS_CMD_EVT_ENABLED)
#define UC_BT_CTRL_LE_VS_CMD_EVT_ENABLED (CONFIG_BT_CTRL_LE_VS_CMD_EVT_ENABLED)
#else
#define UC_BT_CTRL_LE_VS_CMD_EVT_ENABLED (0)
#endif // CONFIG_BT_CTRL_LE_VS_CMD_EVT_ENABLED

#if defined(CONFIG_BT_NIMBLE_ADV_SEND_CONSTANT_DID)
#define UC_BT_CTRL_LE_VS_CONST_EXT_ADV_DID (CONFIG_BT_NIMBLE_ADV_SEND_CONSTANT_DID)
#elif defined(CONFIG_BT_CTRL_LE_VS_CONST_EXT_ADV_DID)
#define UC_BT_CTRL_LE_VS_CONST_EXT_ADV_DID (CONFIG_BT_CTRL_LE_VS_CONST_EXT_ADV_DID)
#else
#define UC_BT_CTRL_LE_VS_CONST_EXT_ADV_DID (0)
#endif // CONFIG_BT_NIMBLE_ADV_SEND_CONSTANT_DID

#if defined(CONFIG_BT_NIMBLE_SCAN_ALLOW_ENH_ADI_FILTER)
#define UC_BT_CTRL_LE_VS_ADI_FILTER_ENABLED (CONFIG_BT_NIMBLE_SCAN_ALLOW_ENH_ADI_FILTER)
#elif defined(CONFIG_BT_CTRL_LE_VS_ADI_FILTER_ENABLED)
#define UC_BT_CTRL_LE_VS_ADI_FILTER_ENABLED (CONFIG_BT_CTRL_LE_VS_ADI_FILTER_ENABLED)
#else
#define UC_BT_CTRL_LE_VS_ADI_FILTER_ENABLED (0)
#endif // CONFIG_BT_NIMBLE_SCAN_ALLOW_ENH_ADI_FILTER

#if defined(CONFIG_BT_LE_CTRL_CHECK_CONNECT_IND_ACCESS_ADDRESS)
#define UC_BT_CTRL_LE_CHECK_CONNECT_IND_ACCESS_ADDRESS (CONFIG_BT_LE_CTRL_CHECK_CONNECT_IND_ACCESS_ADDRESS)
#else
#define UC_BT_CTRL_LE_CHECK_CONNECT_IND_ACCESS_ADDRESS (0)
#endif // CONFIG_BT_LE_CTRL_CHECK_CONNECT_IND_ACCESS_ADDRESS

#if defined(CONFIG_BT_LE_CTRL_LLCP_CONN_UPDATE)
#define UC_BT_CTRL_LE_CONN_UPDATE_PASSED_DISC_FLAG (1 << 0)
#else
#define UC_BT_CTRL_LE_CONN_UPDATE_PASSED_DISC_FLAG (0 << 0)
#endif // CONFIG_BT_LE_CTRL_LLCP_CONN_UPDATE

#if defined(CONFIG_BT_LE_CTRL_LLCP_CHAN_MAP_UPDATE)
#define UC_BT_CTRL_LE_CHAN_UPDATE_PASSED_DISC_FLAG (1 << 1)
#else
#define UC_BT_CTRL_LE_CHAN_UPDATE_PASSED_DISC_FLAG (0 << 1)
#endif // CONFIG_BT_LE_CTRL_LLCP_CHAN_MAP_UPDATE

#if defined(CONFIG_BT_LE_CTRL_LLCP_PHY_UPDATE)
#define UC_BT_CTRL_LE_PHY_UPDATE_PASSED_DISC_FLAG (1 << 2)
#else
#define UC_BT_CTRL_LE_PHY_UPDATE_PASSED_DISC_FLAG (0 << 2)
#endif // CONFIG_BT_LE_CTRL_LLCP_PHY_UPDATE

#define UC_BT_CTRL_LLCP_INSTANT_PASSED_DISC_FLAGS                                                  \
    (UC_BT_CTRL_LE_CONN_UPDATE_PASSED_DISC_FLAG | UC_BT_CTRL_LE_CHAN_UPDATE_PASSED_DISC_FLAG |     \
     UC_BT_CTRL_LE_PHY_UPDATE_PASSED_DISC_FLAG)


#if defined(CONFIG_BT_CTRL_SCAN_BACKOFF_UPPERLIMITMAX)
#define UC_BT_CTRL_LE_SCAN_BACKOFF_UPPERLIMITMAX (CONFIG_BT_CTRL_SCAN_BACKOFF_UPPERLIMITMAX)
#else
#define UC_BT_CTRL_LE_SCAN_BACKOFF_UPPERLIMITMAX (256)
#endif // CONFIG_BT_CTRL_SCAN_BACKOFF_UPPERLIMITMAX

#if defined(CONFIG_BT_LE_CTRL_CHAN_ASS_EN)
#define UC_BT_CTRL_LE_CHAN_ASS_ENABLED (CONFIG_BT_LE_CTRL_CHAN_ASS_EN)
#else
#define UC_BT_CTRL_LE_CHAN_ASS_ENABLED (0)
#endif // CONFIG_BT_LE_CTRL_CHAN_ASS_EN

#if defined(CONFIG_BT_LE_CTRL_ADV_DATA_LENGTH_ZERO_AUX)
#define UC_BT_CTRL_LE_ADV_DATA_LENGTH_ZERO_AUX (CONFIG_BT_LE_CTRL_ADV_DATA_LENGTH_ZERO_AUX)
#else
#define UC_BT_CTRL_LE_ADV_DATA_LENGTH_ZERO_AUX (1)
#endif // CONFIG_BT_LE_CTRL_ADV_DATA_LENGTH_ZERO_AUX

#if defined(CONFIG_BT_LE_PTR_CHECK_ENABLED)
#define UC_BT_CTRL_LE_PTR_CHECK_ENABLED (CONFIG_BT_LE_PTR_CHECK_ENABLED)
#else
#define UC_BT_CTRL_LE_PTR_CHECK_ENABLED (0)
#endif // CONFIG_BT_LE_PTR_CHECK_ENABLED

#if defined(CONFIG_BT_LE_CTRL_ADV_EVENT_INC_ON_FULL_TX_EN)
#define UC_BT_CTRL_LE_ADV_EVENT_INC_ON_FULL_TX_EN (1 << 0)
#else
#define UC_BT_CTRL_LE_ADV_EVENT_INC_ON_FULL_TX_EN (0)
#endif // BT_LE_CTRL_ADV_EVENT_INC_ON_FULL_TX_EN

#if defined(CONFIG_BT_LE_CTRL_ADV_CH38_39_TX_AVOID_CONFLICT_EN)
#define UC_BT_CTRL_LE_ADV_CH38_39_TX_AVOID_CONFLICT_EN (1 << 1)
#else
#define UC_BT_CTRL_LE_ADV_CH38_39_TX_AVOID_CONFLICT_EN (0)
#endif // BT_LE_CTRL_ADV_CH38_39_TX_AVOID_CONFLICT_EN

#if defined(CONFIG_BT_LE_ADV_CH39_TXPWR_CONFIG_SEPARATELY_EN)
#define UC_BT_ADV__LECH39_TXPWR_CONFIG_SEPARATELY_EN (1 << 2)
#define UC_BT_CTRL_LE_CH39_TX_PWR_DBM (CONFIG_BT_LE_DFT_CH39_TX_POWER_LEVEL_DBM_EFF)
#else
#define UC_BT_ADV__LECH39_TXPWR_CONFIG_SEPARATELY_EN (0)
#define UC_BT_CTRL_LE_CH39_TX_PWR_DBM (CONFIG_BT_LE_DFT_TX_POWER_LEVEL_DBM_EFF)
#endif // BT_LE_ADV_CH39_TXPWR_CONFIG_SEPARATELY_EN

#if defined(CONFIG_BT_LE_CTRL_ADV_TX_CONTINUE_WHEN_EXCEED_ITVL_EN)
#define UC_BT_CTRL_LE_ADV_TX_CONTINUE_WHEN_EXCEED_ITVL_EN (1 << 3)
#else
#define UC_BT_CTRL_LE_ADV_TX_CONTINUE_WHEN_EXCEED_ITVL_EN (0)
#endif // BT_LE_CTRL_ADV_TX_CONTINUE_WHEN_EXCEED_ITVL_EN

#if defined(CONFIG_BT_LE_CTRL_ADV_RAND_CH_IDX_EN)
#define UC_BT_CTRL_LE_ADV_RAND_CH_IDX_EN (1 << 4)
#else
#define UC_BT_CTRL_LE_ADV_RAND_CH_IDX_EN (0)
#endif // BT_LE_CTRL_ADV_RAND_CH_IDX_EN

#define UC_BT_CTRL_LE_ADV_TX_OPTIONS                                                               \
    (UC_BT_CTRL_LE_ADV_EVENT_INC_ON_FULL_TX_EN | UC_BT_CTRL_LE_ADV_CH38_39_TX_AVOID_CONFLICT_EN |  \
     UC_BT_ADV__LECH39_TXPWR_CONFIG_SEPARATELY_EN |                                                \
     UC_BT_CTRL_LE_ADV_TX_CONTINUE_WHEN_EXCEED_ITVL_EN | UC_BT_CTRL_LE_ADV_RAND_CH_IDX_EN)

#if defined(CONFIG_BT_LE_CTRL_FAST_CONN_DATA_TX_EN)
#define UC_BT_CTRL_LE_FAST_CONN_DATA_TX_EN (CONFIG_BT_LE_CTRL_FAST_CONN_DATA_TX_EN)
#else
#define UC_BT_CTRL_LE_FAST_CONN_DATA_TX_EN (0)
#endif // CONFIG_BT_LE_CTRL_FAST_CONN_DATA_TX_EN

#define UC_BT_CTRL_LE_SCHED_PRIO_LVL_CFG                                                           \
    ((CONFIG_BT_LE_DFT_SYNC_SCHED_PRIO_LEVEL << 4) |                                               \
     (CONFIG_BT_LE_DFT_PERIODIC_ADV_SCHED_PRIO_LEVEL << 2) |                                       \
     (CONFIG_BT_LE_DFT_ADV_SCHED_PRIO_LEVEL))

#if defined(CONFIG_BT_LE_EXT_ADV_RESERVED_MEMORY_COUNT)
#define UC_BT_CTRL_LE_ADV_SM_RESERVE_CNT (CONFIG_BT_LE_EXT_ADV_RESERVED_MEMORY_COUNT)
#else
#define UC_BT_CTRL_LE_ADV_SM_RESERVE_CNT (0)
#endif // CONFIG_BT_LE_EXT_ADV_RESERVED_MEMORY_COUNT

#if defined(CONFIG_BT_LE_CONN_RESERVED_MEMORY_COUNT)
#define UC_BT_CTRL_LE_CONN_SM_RESERVE_CNT (CONFIG_BT_LE_CONN_RESERVED_MEMORY_COUNT)
#else
#define UC_BT_CTRL_LE_CONN_SM_RESERVE_CNT (0)
#endif // CONFIG_BT_LE_CONN_RESERVED_MEMORY_COUNT

#if defined(CONFIG_BT_LE_CTRL_SLV_FAST_RX_CONN_DATA_EN)
#define UC_BT_CTRL_LE_SLV_FAST_RX_CONN_DATA_EN (CONFIG_BT_LE_CTRL_SLV_FAST_RX_CONN_DATA_EN)
#else
#define UC_BT_CTRL_LE_SLV_FAST_RX_CONN_DATA_EN (0)
#endif // CONFIG_BT_LE_CTRL_SLV_FAST_RX_CONN_DATA_EN

#if defined(CONFIG_BT_LE_CTRL_DL_ITVL_PHY_SYNC_EN)
#define UC_BT_CTRL_LE_DL_ITVL_PHY_SYNC_EN (CONFIG_BT_LE_CTRL_DL_ITVL_PHY_SYNC_EN)
#else
#define UC_BT_CTRL_LE_DL_ITVL_PHY_SYNC_EN (0)
#endif // CONFIG_BT_LE_CTRL_DL_ITVL_PHY_SYNC_EN

#if defined(CONFIG_BT_NIMBLE_SCAN_ALLOW_ENH_ADI_FILTER)
#define UC_BT_CTRL_LE_SCAN_ENH_ADI_FILTER (CONFIG_BT_NIMBLE_SCAN_ALLOW_ENH_ADI_FILTER)
#elif defined(CONFIG_BT_CTRL_LE_VS_ADI_FILTER_ENABLED)
#define UC_BT_CTRL_LE_SCAN_ENH_ADI_FILTER (CONFIG_BT_CTRL_LE_VS_ADI_FILTER_ENABLED)
#else
#define UC_BT_CTRL_LE_SCAN_ENH_ADI_FILTER (0)
#endif // CONFIG_BT_NIMBLE_SCAN_ALLOW_ENH_ADI_FILTER

#if defined(CONFIG_BT_LE_DFT_TX_POWER_LEVEL_DBM_EFF)
#define UC_BT_CTRL_LE_DFT_TX_POWER_LEVEL_DBM_EFF (CONFIG_BT_LE_DFT_TX_POWER_LEVEL_DBM_EFF)
#else
#define UC_BT_CTRL_LE_DFT_TX_POWER_LEVEL_DBM_EFF (9)
#endif // CONFIG_BT_LE_DFT_TX_POWER_LEVEL_DBM_EFF

#ifdef CONFIG_BT_CTRL_LE_SUPPORT_MEM_RES
#define UC_BT_CTRL_LE_SUPPORT_MEM_RES (CONFIG_BT_CTRL_LE_SUPPORT_MEM_RES)
#else
#define UC_BT_CTRL_LE_SUPPORT_MEM_RES (0)
#endif // CONFIG_BT_CTRL_LE_SUPPORT_MEM_RES

/* Unchanged configuration */

#define BLE_LL_CTRL_PROC_TIMEOUT_MS_N (40000) /* ms */

#define BLE_LL_CFG_NUM_HCI_CMD_PKTS_N (1)

#define BLE_LL_SCHED_ADV_MAX_USECS_N (852)

#define BLE_LL_SCHED_DIRECT_ADV_MAX_USECS_N (502)

#define BLE_LL_SCHED_MAX_ADV_PDU_USECS_N (376)

#define BLE_LL_SUB_VERS_NR_N (0x0000)

#define BLE_LL_JITTER_USECS_N (16)

#define BLE_PHY_MAX_PWR_DBM_N (10)

#define BLE_LL_CONN_DEF_AUTH_PYLD_TMO_N (3000)

#define RTC_FREQ_N (32768) /* in Hz */

#define BLE_LL_TX_PWR_DBM_N (9)

#ifdef CONFIG_BT_LE_BQB_TEST_EN
#define RUN_BQB_TEST (CONFIG_BT_LE_BQB_TEST_EN)
#else
#define RUN_BQB_TEST (0)
#endif // CONFIG_BT_LE_BQB_TEST_EN

#define RUN_QA_TEST (0)
#define NIMBLE_DISABLE_SCAN_BACKOFF (0)

#ifdef __cplusplus
}
#endif

#endif /* __BLE_USER_CFG_H__ */
