#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := onoff_client

COMPONENT_ADD_INCLUDEDIRS := components/include

EXTRA_COMPONENT_DIRS := $(IDF_PATH)/examples/bluetooth/esp_ble_mesh/common_components/button

include $(IDF_PATH)/make/project.mk
