#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := modbus_master

EXTRA_COMPONENT_DIRS := ../../../
EXTRA_COMPONENT_DIRS += ../../mb_example_common
EXCLUDE_COMPONENTS := examples test freemodbus

include $(IDF_PATH)/make/project.mk
