.. list-table::
  :header-rows: 1
  :widths: 20 10 10 20 20 20

  * - CPU frequency
    - DFS
    - DTIM
    - Average current (mA)
    - Max current (mA)
    - Min current (mA)

  * - 160 MHz
    - ON
    - 1
    - 14.37
    - 84.40
    - 10.02

  * - 160 MHz
    - OFF
    - 1
    - 27.48
    - 87.55
    - 26.92

  * - 160 MHz
    - ON
    - 3
    - 13.9
    - 83.9
    - 10.13

  * - 160 MHz
    - OFF
    - 3
    - 27.08
    - 87.74
    - 26.91

  * - 160 MHz
    - ON
    - 10
    - 13.71
    - 82.77
    - 10.04

  * - 160 MHz
    - OFF
    - 10
    - 26.85
    - 88.07
    - 26.7
