ifdef CONFIG_IDF_TARGET_ESP32S2BETA
ULP_BINUTILS_PREFIX ?= esp32s2ulp-elf-
else 
ULP_BINUTILS_PREFIX ?= esp32ulp-elf-
endif
#
export ULP_AS := $(ULP_BINUTILS_PREFIX)as
export ULP_LD := $(ULP_BINUTILS_PREFIX)ld
export ULP_OBJCOPY := $(ULP_BINUTILS_PREFIX)objcopy
export ULP_OBJDUMP := $(ULP_BINUTILS_PREFIX)objdump
export ULP_LD_TEMPLATE := $(IDF_PATH)/components/ulp/ld/esp32.ulp.ld
export ULP_NM := $(ULP_BINUTILS_PREFIX)nm
export ULP_MAP_GEN := $(IDF_PATH)/components/ulp/esp32ulp_mapgen.py
