SOURCE_FILES := \
	$(addprefix ../src/, \
	diskio.c \
	ff.c \
	ffsystem.c \
	ffunicode.c \
	diskio_wl.c \
	)

INCLUDE_DIRS := \
	. \
	../src \
	$(addprefix ../../spi_flash/sim/stubs/, \
	app_update/include \
	driver/include \
	esp32/include \
	freertos/include \
	log/include \
	newlib/include \
	sdmmc/include \
	vfs/include \
	) \
	$(addprefix ../../../components/, \
	esp_rom/include \
	xtensa/include \
	xtensa/esp32/include \
	soc/esp32/include \
	esp32/include \
	esp_common/include \
	bootloader_support/include \
	app_update/include \
	spi_flash/include \
	wear_levelling/include \
	)
