SOURCE_FILES := \
	$(addprefix ../src/, \
		ff.c \
		ffunicode.c \
	) \
	$(addprefix ../diskio/,\
		diskio.c \
		diskio_wl.c \
	) \
	../port/linux/ffsystem.c

INCLUDE_DIRS := \
	. \
	../diskio \
	../src \
	$(addprefix ../../spi_flash/sim/stubs/, \
		app_update/include \
		driver/include \
		freertos/include \
		newlib/include \
		sdmmc/include \
		vfs/include \
	) \
	$(addprefix ../../../components/, \
		esp_rom/include \
		esp_hw_support/include \
		esp_hw_support/include/soc \
		esp_system/include \
		log/include \
		xtensa/include \
		xtensa/esp32/include \
		soc/esp32/include \
                heap/include \
		soc/include \
		esp32/include \
		esp_common/include \
		bootloader_support/include \
		bootloader_support/bootloader_flash/include \
		app_update/include \
		hal/include \
		spi_flash/include \
		wear_levelling/include \
		esp_partition/include \
	)
