#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := simple_sniffer

EXTRA_COMPONENT_DIRS += $(IDF_PATH)/examples/common_components/pcap

include $(IDF_PATH)/make/project.mk
