/*
 * SPDX-FileCopyrightText: 2025-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

/*
 * @brief BitScrambler attachment targets
 * Note that these are the values written to HP_SYSTEM_BITSCRAMBLER_PERI_SEL_REG.
 */

#define SOC_BITSCRAMBLER_ATTACH_NONE      -1
#define SOC_BITSCRAMBLER_ATTACH_LCD_CAM   1
#define SOC_BITSCRAMBLER_ATTACH_GPSPI2    2
#define SOC_BITSCRAMBLER_ATTACH_GPSPI3    3
#define SOC_BITSCRAMBLER_ATTACH_PARL_IO   4
#define SOC_BITSCRAMBLER_ATTACH_AES       5
#define SOC_BITSCRAMBLER_ATTACH_SHA       6
#define SOC_BITSCRAMBLER_ATTACH_ADC       7
#define SOC_BITSCRAMBLER_ATTACH_I2S0CH0   8
#define SOC_BITSCRAMBLER_ATTACH_I2S0CH1   9
#define SOC_BITSCRAMBLER_ATTACH_I2S0CH2   10
#define SOC_BITSCRAMBLER_ATTACH_I2S0CH3   11
#define SOC_BITSCRAMBLER_ATTACH_I2S1CH0   12
#define SOC_BITSCRAMBLER_ATTACH_I2S1CH1   13
#define SOC_BITSCRAMBLER_ATTACH_I2S1CH2   14
#define SOC_BITSCRAMBLER_ATTACH_I2S1CH3   15
#define SOC_BITSCRAMBLER_ATTACH_UHCI      16
#define SOC_BITSCRAMBLER_ATTACH_RMT       17
#define SOC_BITSCRAMBLER_ATTACH_MAX       17
