#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := esp_ot_cli

EXTRA_COMPONENT_DIRS = $(IDF_PATH)/examples/common_components/iperf

include $(IDF_PATH)/make/project.mk
