/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: custom_config.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "custom_config.pb-c.h"
void   custom_config_request__init
                     (CustomConfigRequest         *message)
{
  static const CustomConfigRequest init_value = CUSTOM_CONFIG_REQUEST__INIT;
  *message = init_value;
}
size_t custom_config_request__get_packed_size
                     (const CustomConfigRequest *message)
{
  assert(message->base.descriptor == &custom_config_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t custom_config_request__pack
                     (const CustomConfigRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &custom_config_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t custom_config_request__pack_to_buffer
                     (const CustomConfigRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &custom_config_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CustomConfigRequest *
       custom_config_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CustomConfigRequest *)
     protobuf_c_message_unpack (&custom_config_request__descriptor,
                                allocator, len, data);
}
void   custom_config_request__free_unpacked
                     (CustomConfigRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &custom_config_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   custom_config_response__init
                     (CustomConfigResponse         *message)
{
  static const CustomConfigResponse init_value = CUSTOM_CONFIG_RESPONSE__INIT;
  *message = init_value;
}
size_t custom_config_response__get_packed_size
                     (const CustomConfigResponse *message)
{
  assert(message->base.descriptor == &custom_config_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t custom_config_response__pack
                     (const CustomConfigResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &custom_config_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t custom_config_response__pack_to_buffer
                     (const CustomConfigResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &custom_config_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CustomConfigResponse *
       custom_config_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CustomConfigResponse *)
     protobuf_c_message_unpack (&custom_config_response__descriptor,
                                allocator, len, data);
}
void   custom_config_response__free_unpacked
                     (CustomConfigResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &custom_config_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor custom_config_request__field_descriptors[2] =
{
  {
    "info",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CustomConfigRequest, info),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CustomConfigRequest, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned custom_config_request__field_indices_by_name[] = {
  0,   /* field[0] = info */
  1,   /* field[1] = version */
};
static const ProtobufCIntRange custom_config_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor custom_config_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CustomConfigRequest",
  "CustomConfigRequest",
  "CustomConfigRequest",
  "",
  sizeof(CustomConfigRequest),
  2,
  custom_config_request__field_descriptors,
  custom_config_request__field_indices_by_name,
  1,  custom_config_request__number_ranges,
  (ProtobufCMessageInit) custom_config_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor custom_config_response__field_descriptors[2] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CustomConfigResponse, status),
    &custom_config_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dummy",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CustomConfigResponse, dummy),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned custom_config_response__field_indices_by_name[] = {
  1,   /* field[1] = dummy */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange custom_config_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor custom_config_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CustomConfigResponse",
  "CustomConfigResponse",
  "CustomConfigResponse",
  "",
  sizeof(CustomConfigResponse),
  2,
  custom_config_response__field_descriptors,
  custom_config_response__field_indices_by_name,
  1,  custom_config_response__number_ranges,
  (ProtobufCMessageInit) custom_config_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue custom_config_status__enum_values_by_number[2] =
{
  { "ConfigSuccess", "CUSTOM_CONFIG_STATUS__ConfigSuccess", 0 },
  { "ConfigFail", "CUSTOM_CONFIG_STATUS__ConfigFail", 1 },
};
static const ProtobufCIntRange custom_config_status__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex custom_config_status__enum_values_by_name[2] =
{
  { "ConfigFail", 1 },
  { "ConfigSuccess", 0 },
};
const ProtobufCEnumDescriptor custom_config_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CustomConfigStatus",
  "CustomConfigStatus",
  "CustomConfigStatus",
  "",
  2,
  custom_config_status__enum_values_by_number,
  2,
  custom_config_status__enum_values_by_name,
  1,
  custom_config_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
