/*
 * SPDX-FileCopyrightText: 2022 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include "soc/interrupts.h"

const char *const esp_isr_names[] = {
    [0] = "WIFI_MAC",
    [1] = "WIFI_MAC_NMI",
    [2] = "WIFI_PWR",
    [3] = "WIFI_BB",
    [4] = "BT_MAC",
    [5] = "BT_BB",
    [6] = "BT_BB_NMI",
    [7] = "LP_TIMER",
    [8] = "COEX",
    [9] = "BLE_TIMER",
    [10] = "BLE_SEC",
    [11] = "I2C_MASTER",
    [12] = "ZB_MAC",
    [13] = "PMU",
    [14] = "EFUSE",
    [15] = "LP_RTC_TIMER",
    [16] = "LP_UART",
    [17] = "LP_I2C",
    [18] = "LP_WDT",
    [19] = "LP_PERI_TIMEOUT",
    [20] = "LP_APM_M0",
    [21] = "LP_APM_M1",
    [22] = "CPU_FROM_CPU_0",
    [23] = "CPU_FROM_CPU_1",
    [24] = "CPU_FROM_CPU_2",
    [25] = "CPU_FROM_CPU_3",
    [26] = "ASSIST_DEBUG",
    [27] = "TRACE",
    [28] = "CACHE",
    [29] = "CPU_PERI_TIMEOUT",
    [30] = "GPIO_INTERRUPT_PRO",
    [31] = "GPIO_INTERRUPT_PRO_NMI",
    [32] = "PAU",
    [33] = "HP_PERI_TIMEOUT",
    [34] = "MODEM_PERI_TIMEOUT",
    [35] = "HP_APM_M0",
    [36] = "HP_APM_M1",
    [37] = "HP_APM_M2",
    [38] = "HP_APM_M3",
    [39] = "LP_APM0",
    [40] = "MSPI",
    [41] = "I2S0",
    [42] = "UHCI0",
    [43] = "UART0",
    [44] = "UART1",
    [45] = "LEDC",
    [46] = "CAN0",
    [47] = "CAN1",
    [48] = "USB",
    [49] = "RMT",
    [50] = "I2C_EXT0",
    [51] = "TG0_T0",
    [52] = "TG0_T1",
    [53] = "TG0_WDT",
    [54] = "TG1_T0",
    [55] = "TG1_T1",
    [56] = "TG1_WDT",
    [57] = "SYSTIMER_TARGET0",
    [58] = "SYSTIMER_TARGET1",
    [59] = "SYSTIMER_TARGET2",
    [60] = "APB_ADC",
    [61] = "PWM",
    [62] = "PCNT",
    [63] = "PARL_IO",
    [64] = "SLC0",
    [65] = "SLC1",
    [66] = "DMA_IN_CH0",
    [67] = "DMA_IN_CH1",
    [68] = "DMA_IN_CH2",
    [69] = "DMA_OUT_CH0",
    [70] = "DMA_OUT_CH1",
    [71] = "DMA_OUT_CH2",
    [72] = "GPSPI2",
    [73] = "AES",
    [74] = "SHA",
    [75] = "RSA",
    [76] = "ECC",
};
