SUPPORTED_TOOLCHAIN_COMMIT_DESC = esp-2020r1
SUPPORTED_TOOLCHAIN_GCC_VERSIONS = 8.2.0

CURRENT_TOOLCHAIN_COMMIT_DESC = esp-2020r1
CURRENT_TOOLCHAIN_COMMIT_DESC_SHORT = esp-2020r1
CURRENT_TOOLCHAIN_GCC_VERSION = 8.2.0
