#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := hello-world

EXTRA_CPPFLAGS := \
	-Wall \
	-Wextra \
	-Werror

include $(IDF_PATH)/make/project.mk

