# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/esp_riscv_trace/test_apps:
  disable:
    - if: SOC_RISCV_TRACE_SUPPORTED != 1
    - if: CONFIG_NAME == "psram" and SOC_SPIRAM_SUPPORTED != 1
  depends_components:
    - esp_riscv_trace
