# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

components/bt/common/ble_log/test_apps/ble_log_perf_test:
  disable:
    - if: IDF_TARGET != "none"
      temporary: true
      reason: No BLE Log test runners are available yet
  depends_components:
    - bt

components/bt/common/ble_log/test_apps/ble_log_test:
  disable:
    - if: IDF_TARGET != "none"
      temporary: true
      reason: No BLE Log test runners are available yet
  depends_components:
    - bt
